### ISSUE TITLE
No work :(

### ISSUE THREAD

**Issue by yavko** [CauldronJS/Spigot#1]
# ok so i just got the plugin installed and, im having errors i just added it to my server and ran this is what it shows every time 

<details>
<summary>Details</summary>

[23:49:44 INFO]: [Cauldron] Enabling Cauldron v${project.version}*
[23:49:45 ERROR]: [Cauldron] Failed to find Cauldron entry point
[23:49:45 ERROR]: [Cauldron] java.io.FileNotFoundException: /Users/yavor/yatopia/plugins/Cauldron/lib/internal/bootstrap/loader.js
[23:49:46 ERROR]: Error occurred while enabling Cauldron v${project.version} (Is it up to date?)
[23:49:46 ERROR]: Suspected Plugins:
[23:49:46 ERROR]: 	Cauldron{enabled,ver=${project.version},path=plugins/Cauldron-Spigot-1.0.0.jar}
[23:49:46 ERROR]: Exception details below:
java.lang.NullPointerException: null
	at com.cauldronjs.Isolate.runEntry(Isolate.java:145) ~[?:?]
	at com.cauldronjs.Cauldron.onEnable(Cauldron.java:33) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:595) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:321) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1077) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-116]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[23:49:46 INFO]: [Cauldron] Disabling Cauldron v${project.version}

</details>

Im using 

<table>
<tr>
	<td>Im using

<tr>
	<td>Yatopia (Tuinity Fork which is a paper fork which is a spigot fork whatever)
<tr>
	<td> Graalvm 11.0.11
</table>

**Comment by ItsSpyce** [comment]
Ensure that the scripts repository is cloned. That being said, active development on this plugin has grinded to a near stop due to other responsibilities and projects.
